"""Setup wizard Flask application.

Note: CSRF protection not included - this wizard runs locally during initial setup only
and is not exposed to the network. Do not expose this app to external networks.
"""
import os
from flask import Flask, render_template, request, jsonify
from pathlib import Path
import sys

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.state_data import load_state, get_all_states
from setup.validators import (
    validate_airtable_key,
    validate_anthropic_key,
    validate_openai_key,
    validate_clio_credentials,
)

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", os.urandom(24).hex())

# Reserved for future wizard state management
wizard_data = {}


def sanitize_env_value(value):
    """Sanitize value for .env file - remove newlines and control chars."""
    if not isinstance(value, str):
        return str(value) if value else ""
    return value.replace("\n", "").replace("\r", "").replace("\x00", "")


@app.route("/")
def index():
    """Welcome page with mode selection."""
    return render_template("index.html")


@app.route("/starter")
def starter():
    """Starter mode wizard."""
    return render_template("starter.html")


@app.route("/api/states")
def get_states():
    """Return list of all available states."""
    states = get_all_states()
    return jsonify(states)


@app.route("/api/state/<abbr>")
def get_state(abbr):
    """Return state data for a specific state."""
    try:
        state = load_state(abbr)
        return jsonify({
            "name": state.name,
            "abbreviation": state.abbreviation,
            "sol_years": state.sol_years,
            "sol_notes": state.sol_notes,
            "counties": state.counties,
            "major_metros": state.major_metros,
            "default_preferred_counties": state.default_preferred_counties,
        })
    except FileNotFoundError:
        return jsonify({"error": f"State not found: {abbr}"}), 404


@app.route("/api/validate/airtable", methods=["POST"])
def validate_airtable():
    """Validate Airtable API key."""
    data = request.json or {}
    result = validate_airtable_key(
        data.get("api_key", ""),
        data.get("base_id", ""),
        data.get("table_id", ""),
    )
    return jsonify({"valid": result.valid, "message": result.message})


@app.route("/api/validate/ai", methods=["POST"])
def validate_ai():
    """Validate AI provider API key."""
    data = request.json or {}
    provider = data.get("provider", "anthropic")
    api_key = data.get("api_key", "")

    if provider == "anthropic":
        result = validate_anthropic_key(api_key)
    else:
        result = validate_openai_key(api_key)

    return jsonify({"valid": result.valid, "message": result.message})


@app.route("/api/generate-config", methods=["POST"])
def generate_config():
    """Generate .env file from wizard data."""
    data = request.json or {}

    # Helper to sanitize and get values
    def get_sanitized(key, default=""):
        return sanitize_env_value(data.get(key, default))

    # Build .env content
    env_lines = [
        "# PI Lead Qualifier Configuration",
        "# Generated by setup wizard",
        "",
        "# Operation Mode",
        f"OPERATION_MODE={get_sanitized('mode', 'starter')}",
        "",
        "# Firm Information",
        f"FIRM_NAME={get_sanitized('firm_name')}",
        f"ATTORNEY_NAME={get_sanitized('attorney_name')}",
        "",
        "# Geographic Settings",
        f"STATE={get_sanitized('state')}",
        f"SOL_YEARS={get_sanitized('sol_years', '3')}",
        f"PREFERRED_COUNTIES={','.join([sanitize_env_value(c) for c in data.get('preferred_counties', [])])}",
        "",
        "# Airtable",
        f"AIRTABLE_API_KEY={get_sanitized('airtable_api_key')}",
        f"AIRTABLE_BASE_ID={get_sanitized('airtable_base_id')}",
        f"AIRTABLE_TABLE_ID={get_sanitized('airtable_table_id')}",
        "",
        "# AI Provider",
        f"AI_PROVIDER={get_sanitized('ai_provider', 'anthropic')}",
    ]

    if data.get('ai_provider') == 'anthropic':
        env_lines.append(f"ANTHROPIC_API_KEY={get_sanitized('ai_api_key')}")
    else:
        env_lines.append(f"OPENAI_API_KEY={get_sanitized('ai_api_key')}")

    # Pro mode additions
    if data.get('mode') == 'pro':
        env_lines.extend([
            "",
            "# Clio Integration (Pro Mode)",
            f"CLIO_CLIENT_ID={get_sanitized('clio_client_id')}",
            f"CLIO_CLIENT_SECRET={get_sanitized('clio_client_secret')}",
            "",
            "# Email Settings (Pro Mode)",
            f"GMAIL_SENDER_EMAIL={get_sanitized('sender_email')}",
            f"GMAIL_INTAKE_EMAIL={get_sanitized('intake_email')}",
            f"GMAIL_NOTIFICATION_EMAIL={get_sanitized('notification_email')}",
        ])

    env_content = "\n".join(env_lines)

    # Write to .env file
    env_path = Path(__file__).parent.parent / ".env"
    with open(env_path, "w") as f:
        f.write(env_content)

    return jsonify({
        "success": True,
        "message": "Configuration saved! You can now run the qualifier.",
        "env_path": str(env_path),
    })


if __name__ == "__main__":
    app.run(debug=os.environ.get("FLASK_DEBUG", "false").lower() == "true", port=8080)
